services:
  backend:
    build:
      context: ./se-project-be-68-2-orangered
    container_name: orangered_backend
    ports:
      - "5000:5000"
    env_file:
      - ./se-project-be-68-2-orangered/config/config.env
    networks:
      - app_network
    restart: unless-stopped

  frontend:
    build:
      context: ./se-project-fe-68-2-orangered
      args:
        BACKEND_URL: http://backend:5000
        NEXT_PUBLIC_BACKEND_URL: http://localhost:5000
    container_name: orangered_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./se-project-fe-68-2-orangered/.env.local
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:5000
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    external: true