FROM node:22.18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
ARG BACKEND_URL
ARG NEXT_PUBLIC_BACKEND_URL
ENV BACKEND_URL=$BACKEND_URL
ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL

RUN npm run build

EXPOSE 3000

CMD ["npm", "start"]